DROP TABLE IF EXISTS "KEY_TABLE";

CREATE TABLE "KEY_TABLE"
(
  id         BIGINT  NOT NULL,
  serial_id  VARCHAR NOT NULL,
  public_key BYTEA   NOT NULL,
  CONSTRAINT PRIMARY_KEY PRIMARY KEY (id)
);

ALTER TABLE "KEY_TABLE"
  OWNER TO postgres;

DROP SEQUENCE IF EXISTS KEY_SEQ;


CREATE SEQUENCE KEY_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 9
  CACHE 1;
ALTER TABLE KEY_SEQ
  OWNER TO postgres;